/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:dc4759e6-752f-40b0-a9d1-411a12345287",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_f0yly7rrw",
    "aws_user_pools_web_client_id": "436ajnjjq9649i6stoaahicnvl",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://n7dryf3okvfmjbnl6v2ns7aph4.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-gbqsai4i4jh2dozcrfokryfpum"
};


export default awsmobile;
